version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://root:example@mongo:27017/mydb?authSource=admin"
    depends_on:
      - mongo
volumes:
  mongo-data: