apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port:    "3000"
    spec:
      containers:
      - name: myapp
        image: asia-southeast1-docker.pkg.dev/sit323-2025-prac10/sit323-repo/my-cloud-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: mongodb://root:example@mongo-service:27017/mydb
